### ISSUE TITLE
Adding Problems

### ISSUE THREAD

**Issue by magicalsoup** [BayviewComputerClub/BayviewJudge-UI#19]
After adding a problem, And passing the test cases, first, I didn't get any points. Secondly, output only problems seems to be not supported as there were no point values given for just output.

**Comment by Seshpenguin** [comment]
I'm closing this one for now. Basically the actually get all the data it needs (like number of batches) from the input cases JSON. For output only problems, just declare an input case thats blank.
`
 [ { "cases": [""], "points": 10 }]`

**Comment by Seshpenguin** [comment]
That Hello World problem seems to be working now. You can safely ignore any SQL errors it's throwing rn, the production server has an outdated database.
