### ISSUE TITLE
Better Editor

### ISSUE THREAD

**Issue by Seshpenguin** [BayviewComputerClub/BayviewJudge-UI#7]
TinyMCE lacks equations and stuff or add a plugin

**Comment by espidev** [comment]
or embed a pdf

**Comment by espidev** [comment]
and just use TeX

**Comment by Seshpenguin** [comment]
please leave this repository immdeidatly o r i will have to ask you even more nicely sorry

**Comment by Seshpenguin** [comment]
We are using embedded PDFs
